services:
  bundle: &bundle
    stdin_open: true
    tty: true
    build:
      context: .
    volumes:
      - bundle:/usr/local/bundle:delegated
      - .:/usr/src/app:delegated
    entrypoint: bundle
    command: check

  graphiql:
    <<: *bundle
    ports:
      - ${PORT}:${PORT}
    command: exec jekyll serve --config "_config.yml,_config.dev.yml"

volumes:
  bundle: {}
