---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: graphiql
spec:
  selector:
    matchLabels:
      app: graphiql
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: graphiql
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: registry-auth
      containers:
        - name: graphiql
          image: ghcr.io/compada/graphiql:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: graphiql-config
          resources:
            requests:
              cpu: 50m
              memory: 200M
            limits:
              cpu: 100m
              memory: 400M
